import type { User, FarmlandListing, EquipmentListing, Booking } from "./types";

export const users: User[] = [
  {
    id: "user1",
    name: "Ibikunle Adam",
    email: "ade@example.com",
    avatar:
      "https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=400",
    role: "farmer",
  },
  {
    id: "user2",
    name: "Chiamaka Nwosu",
    email: "chi@example.com",
    avatar:
      "https://images.unsplash.com/photo-1531384370597-8590413be50a?w=400",
    role: "landowner",
  },
  {
    id: "user3",
    name: "Musa Bello",
    email: "musa@example.com",
    avatar:
      "https://images.unsplash.com/photo-1506863530036-1efeddceb993?w=400",
    role: "equipment-owner",
  },
  {
    id: "user4",
    name: "Fatima Abubakar",
    email: "fatima@example.com",
    avatar:
      "https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=400",
    role: "landowner",
  },
  {
    id: "user5",
    name: "Chukwudi Okonkwo",
    email: "chukwudi@example.com",
    avatar:
      "https://images.unsplash.com/photo-1531384370597-8590413be50a?w=400",
    role: "landowner",
  },
  {
    id: "user6",
    name: "Amina Yusuf",
    email: "amina@example.com",
    avatar: "https://images.unsplash.com/photo-1506863530036-1efeddceb993?w=400",
    role: "landowner",
  },
  {
    id: "user7",
    name: "Oluwaseun Adeyemi",
    email: "seun@example.com",
    avatar:
      "https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=400",
    role: "equipment-owner",
  },
  {
    id: "user8",
    name: "Ngozi Eze",
    email: "ngozi@example.com",
    avatar:
      "https://images.unsplash.com/photo-1531384370597-8590413be50a?w=400",
    role: "equipment-owner",
  },
  {
    id: "user9",
    name: "Ibrahim Suleiman",
    email: "ibrahim@example.com",
    avatar:
      "https://images.unsplash.com/photo-1506863530036-1efeddceb993?w=400",
    role: "landowner",
  },
  {
    id: "user10",
    name: "Blessing Okoro",
    email: "blessing@example.com",
    avatar: "https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=400",
    role: "equipment-owner",
  },
];

export const farmlandListings: FarmlandListing[] = [
  {
    id: "farm1",
    type: "farmland",
    title: "Fertile 50-Acre Farmland in Oyo",
    description:
      "A vast expanse of fertile agricultural land with rolling green fields perfect for cassava and maize cultivation. Comes with access to a nearby stream for irrigation. The soil is a rich loamy type, tested and confirmed for high yield. The land is fenced and secure.",
    price: 150000,
    priceUnit: "per_acre_per_year",
    location: "Ibadan, Oyo",
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800",
      "https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=800",
    ],
    ownerId: "user2",
    size: 50,
    soilType: "Loamy",
    reviews: [
      {
        id: "r1",
        userId: "user1",
        rating: 5,
        comment: "Excellent land, very fertile.",
      },
    ],
    avgRating: 5,
  },
  {
    id: "farm2",
    type: "farmland",
    title: "20-Acre Green Farmland in Enugu",
    description:
      "Well-maintained agricultural land with lush green vegetation and rolling hills. Perfect for crop cultivation with excellent soil quality. Located in a secure area with good road access. Water source available throughout the year.",
    price: 200000,
    priceUnit: "per_acre_per_year",
    location: "Enugu, Enugu",
    images: [
      "/images/farms/farm-02.jpg",
    ],
    ownerId: "user4",
    size: 20,
    soilType: "Sandy Loam",
    reviews: [
      {
        id: "r2",
        userId: "user1",
        rating: 4,
        comment: "Good plantation, but access road needs some work.",
      },
    ],
    avgRating: 4,
  },
  {
    id: "farm3",
    type: "farmland",
    title: "100-Acre Rice Paddy Field",
    description:
      "Expansive, irrigated paddy field suitable for large-scale rice farming. The land is flat and has been professionally leveled. It includes a modern irrigation system powered by solar energy, reducing operational costs.",
    price: 120000,
    priceUnit: "per_acre_per_year",
    location: "Bida, Niger",
    images: [
      "/images/farms/farm-03.jpg",
    ],
    ownerId: "user5",
    size: 100,
    soilType: "Clay",
    reviews: [],
    avgRating: 0,
  },
  {
    id: "farm4",
    type: "farmland",
    title: "10-Acre Greenhouse Vegetable Farm",
    description:
      "Modern greenhouse vegetable farm with controlled environment for year-round production. Perfect for vegetable farming with drip irrigation installed. Located near a major market. The soil is rich and well-drained. Suitable for tomatoes, peppers, and leafy greens.",
    price: 90000,
    priceUnit: "per_acre_per_year",
    location: "Jos, Plateau",
    images: [
      "https://images.unsplash.com/photo-1592982537447-7440770cbfc9?w=800",
    ],
    ownerId: "user6",
    size: 10,
    soilType: "Loamy Sand",
    reviews: [],
    avgRating: 0,
  },
  {
    id: "farm5",
    type: "farmland",
    title: "75-Acre Mixed Crop Farmland",
    description:
      "Spacious agricultural land with diverse crop potential in the fertile belt of Nigeria. The soil is ideal for yam, cassava, and other root crops and has been fallow for 2 years, ensuring high fertility. Good access roads and security.",
    price: 130000,
    priceUnit: "per_acre_per_year",
    location: "Makurdi, Benue",
    images: [
      "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800",
    ],
    ownerId: "user9",
    size: 75,
    soilType: "Sandy Loam",
    reviews: [],
    avgRating: 0,
  },
  {
    id: "farm6",
    type: "farmland",
    title: "30-Acre Coffee/Cocoa Plantation",
    description:
      "A thriving plantation with high-yield trees in a lush tropical setting. The farm has been well-managed with consistent pruning and pest control. Perfect for coffee or cocoa cultivation. Located in a region known for premium agricultural produce.",
    price: 180000,
    priceUnit: "per_acre_per_year",
    location: "Idanre, Ondo",
    images: ["/images/farms/farm-06.jpg"],
    ownerId: "user2",
    size: 30,
    soilType: "Clay Loam",
    reviews: [],
    avgRating: 0,
  },
  {
    id: "farm7",
    type: "farmland",
    title: "5-Acre Livestock Farm Land",
    description:
      "Fenced plot of land suitable for setting up a livestock farm with grazing animals. Comes with a borehole for constant water supply. Close to a major town for easy access to feed and market. Perfect for cattle, goats, or sheep rearing.",
    price: 100000,
    priceUnit: "per_acre_per_year",
    location: "Abeokuta, Ogun",
    images: ["https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800"],
    ownerId: "user4",
    size: 5,
    soilType: "Laterite",
    reviews: [],
    avgRating: 0,
  },
  {
    id: "farm8",
    type: "farmland",
    title: "200-Acre Grazing Land",
    description:
      "Vast open grassland ideal for cattle rearing and grazing. Contains a natural water source and is fenced to prevent straying. The vegetation is a mix of nutritious local grasses.",
    price: 80000,
    priceUnit: "per_acre_per_year",
    location: "Sokoto, Sokoto",
    images: [
      "/images/farms/farm-08.jpg",
    ],
    ownerId: "user5",
    size: 200,
    soilType: "Sandy",
    reviews: [],
    avgRating: 0,
  },
  {
    id: "farm9",
    type: "farmland",
    title: "15-Acre Aquaculture Fish Farm",
    description:
      "Professional aquaculture facility with excavated ponds ready for commercial fish farming. Includes a water inlet and outlet system with proper drainage. The location has a high water table, making it perfect for tilapia, catfish, and other species.",
    price: 110000,
    priceUnit: "per_acre_per_year",
    location: "Epe, Lagos",
    images: [
      "/images/farms/farm-09.jpg",
    ],
    ownerId: "user6",
    size: 15,
    soilType: "Swampy",
    reviews: [],
    avgRating: 0,
  },
  {
    id: "farm10",
    type: "farmland",
    title: "40-Acre Groundnut Farm",
    description:
      "A large plot perfect for groundnut cultivation. The soil is light and sandy, which is optimal for groundnut yield. Mechanized farming is possible due to the flat terrain.",
    price: 95000,
    priceUnit: "per_acre_per_year",
    location: "Kano, Kano",
    images: ["https://images.unsplash.com/photo-1560493676-04071c5f467b?w=800"],
    ownerId: "user9",
    size: 40,
    soilType: "Sandy",
    reviews: [],
    avgRating: 0,
  },
];

export const equipmentListings: EquipmentListing[] = [
  {
    id: "equip1",
    type: "equipment",
    title: "John Deere Tractor 5075E",
    description:
      "A powerful and reliable John Deere tractor available for daily rental. Perfect for plowing, tilling, and planting. Maintained regularly and in excellent working condition. Comes with an experienced operator if needed, for an extra fee.",
    price: 75000,
    priceUnit: "per_day",
    location: "Kaduna, Kaduna",
    images: [
      "https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=800",
    ],
    ownerId: "user3",
    category: "Tractor",
    condition: "used",
    reviews: [
      {
        id: "r3",
        userId: "user1",
        rating: 4,
        comment: "Good tractor, got the job done.",
      },
    ],
    avgRating: 4,
  },
  {
    id: "equip2",
    type: "equipment",
    title: "Agricultural Harvesting Equipment",
    description:
      "High-capacity harvesting equipment for wheat, maize, and soybeans. Modern agricultural machinery for efficient crop harvesting. Available for rent with a skilled operator. Can cover up to 30 acres per day. Booking in advance is recommended during peak season.",
    price: 250000,
    priceUnit: "per_day",
    location: "Kano, Kano",
    images: ['/images/machineries/machine-2.jpg'],
    ownerId: "user7",
    category: "Harvester",
    condition: "used",
    reviews: [
      {
        id: "r4",
        userId: "user1",
        rating: 5,
        comment: "Very efficient machine.",
      },
    ],
    avgRating: 5,
  },
  {
    id: "equip3",
    type: "equipment",
    title: "Combine Harvester",
    description: "High-capacity combine harvester for efficient grain harvesting. Modern agricultural machinery designed for wheat, maize, and soybeans. Available with skilled operator for large-scale operations. Can harvest up to 50 acres per day during peak season.",
    price: 350000,
    priceUnit: "per_day",
    location: "Makurdi, Benue",
    images: ['/images/machineries/machine-3.jpg'],
    ownerId: "user8",
    category: "Harvester",
    condition: "used",
    reviews: [],
    avgRating: 0,
  },
  {
    id: "equip4",
    type: "equipment",
    title: "Agricultural Planter/Seeder",
    description: "Precision planter for accurate seed sowing in rows. Ideal for maize, beans, and other crops. Ensures uniform spacing and depth for optimal germination. Easy to attach to tractors and suitable for medium to large farms.",
    price: 45000,
    priceUnit: "per_day",
    location: "Ilorin, Kwara",
    images: ['/images/machineries/machine-4.jpg'],
    ownerId: "user10",
    category: "Planter",
    condition: "new",
    reviews: [],
    avgRating: 0,
  },
  {
    id: "equip5",
    type: "equipment",
    title: "Wheel Rake/Hay Rake",
    description: "Efficient wheel rake for gathering and windrowing hay and forage crops. Ideal for post-harvest field operations. Reduces manual labor and speeds up the drying process for better quality feed.",
    price: 25000,
    priceUnit: "per_day",
    location: "Zaria, Kaduna",
    images: ['/images/machineries/machine-5.jpg'],
    ownerId: "user7",
    category: "Rake",
    condition: "used",
    reviews: [],
    avgRating: 0,
  },
  {
    id: "equip6",
    type: "equipment",
    title: "Combine Harvester",
    description: "Heavy-duty combine harvester for large-scale grain harvesting. Equipped with modern threshing technology for wheat, rice, and maize. Requires skilled operator and suitable for commercial farming operations covering 40+ acres daily.",
    price: 400000,
    priceUnit: "per_day",
    location: "Minna, Niger",
    images: ['/images/machineries/machine-6.jpg'],
    ownerId: "user3",
    category: "Harvester",
    condition: "used",
    reviews: [],
    avgRating: 0,
  },
  {
    id: "equip7",
    type: "equipment",
    title: "Cultivator/Disc Harrow",
    description: "Versatile tillage equipment for soil preparation and weed control. Disc harrow design breaks up soil clods and incorporates crop residues. Suitable for secondary tillage operations on various soil types.",
    price: 35000,
    priceUnit: "per_day",
    location: "Umuahia, Abia",
    images: ['/images/machineries/machine-7.jpg'],
    ownerId: "user8",
    category: "Cultivator",
    condition: "used",
    reviews: [],
    avgRating: 0,
  },
  {
    id: "equip8",
    type: "equipment",
    title: "Self-propelled Root Crop Harvester",
    description: "Specialized harvester for root crops like cassava, potatoes, and yams. Self-propelled for efficient operation in various field conditions. Includes cleaning and sorting mechanisms for high-quality produce.",
    price: 180000,
    priceUnit: "per_day",
    location: "Bauchi, Bauchi",
    images: ['/images/machineries/machine-8.jpg'],
    ownerId: "user10",
    category: "Harvester",
    condition: "new",
    reviews: [],
    avgRating: 0,
  },
  {
    id: "equip9",
    type: "equipment",
    title: "Grain Cart/Farm Trailer",
    description: "Large-capacity grain cart for transporting harvested crops from field to storage. High-volume trailer with hydraulic unloading for efficiency. Essential for large-scale grain operations.",
    price: 30000,
    priceUnit: "per_day",
    location: "Akure, Ondo",
    images: ['/images/machineries/machine-10.jpg'],
    ownerId: "user7",
    category: "Trailer",
    condition: "used",
    reviews: [],
    avgRating: 0,
  },
  {
    id: "equip10",
    type: "equipment",
    title: "Forage Harvester/Silage Chopper",
    description: "Specialized forage harvester for chopping grass, maize, and other forage crops into silage. High-capacity machine for livestock feed production. Reduces harvest time and improves feed quality.",
    price: 120000,
    priceUnit: "per_day",
    location: "Ogbomosho, Oyo",
    images: ['/images/machineries/machine-9.jpg'],
    ownerId: "user8",
    category: "Harvester",
    condition: "used",
    reviews: [],
    avgRating: 0,
  },
];

export const bookings: Booking[] = [
  {
    id: "booking1",
    listingId: "equip1",
    listingTitle: "John Deere Tractor 5075E",
    userId: "user1",
    startDate: new Date("2024-08-10"),
    endDate: new Date("2024-08-12"),
    totalPrice: 150000,
    status: "confirmed",
  },
  {
    id: "booking2",
    listingId: "equip2",
    listingTitle: "New Holland Combine Harvester",
    userId: "user1",
    startDate: new Date("2024-09-01"),
    endDate: new Date("2024-09-05"),
    totalPrice: 1250000,
    status: "pending",
  },
];

export const allListings = [...farmlandListings, ...equipmentListings];
